name: flex
description: "UST Social Media App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_storage: ^2.1.1
  get: ^4.6.6
  form_validator: ^2.1.1
  flutter_dotenv: ^5.2.1
  supabase_flutter: ^2.8.0
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  uuid: ^4.5.1
  jiffy: ^6.3.1
  flutter_native_splash: ^2.4.2
  dynamic_color: ^1.7.0
  flutter_linkify: ^6.0.0
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
  sendgrid_mailer: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - .env

flutter_native_splash:
  android: true
  ios: true
  web: false

  background_image: "assets/image/background.png"
  image: "assets/image/splash.png"
  branding: "assets/image/branding.png"

  android_12:
    color: "#242424"
    image: "assets/image/logo_android.png"
    branding: "assets/image/branding_android.png"
